import { useI18n, type Language } from '../i18n';

export type ProtectionCopy = {
  title: string;
  activeTitle: string;
  activeBody: string;
  lockedTitle: string;
  lockedBody: string;
  managePlan: string;
  overview: string;
  lastLocation: string;
  locationCurrent: string;
  locationStale: string;
  locationNever: string;
  separationAlerts: string;
  phoneProtection: string;
  ready: string;
  stale: string;
  notConfigured: string;
  replacement: string;
  eligible: string;
  notEligible: string;
  on: string;
  off: string;
  safeZones: string;
  safeZonesBody: string;
  addZone: string;
  zoneLimit: string;
  emptyZonesTitle: string;
  emptyZonesBody: string;
  loading: string;
  loadError: string;
  retry: string;
  trackerInside: string;
  trackerOutside: string;
  awaitingEvaluation: string;
  lastEvaluated: string;
  paused: string;
  newZone: string;
  editZone: string;
  zoneName: string;
  latitude: string;
  longitude: string;
  radius: string;
  radiusHint: string;
  useTrackerLocation: string;
  invalidName: string;
  invalidCoordinates: string;
  invalidRadius: string;
  zoneCreated: string;
  zoneUpdated: string;
  zoneDeleted: string;
  deleteTitle: string;
  deleteBody: string;
  deleteAction: string;
  saveError: string;
  limitError: string;
  homeTitle: string;
  homeBody: string;
  homeLocked: string;
};

const copies: Record<Language, ProtectionCopy> = {
  en: {
    title: 'Protection',
    activeTitle: 'Phone-aware protection is active',
    activeBody: 'Pinkeva combines your phone, tracker reports, and safe zones to reduce false alerts.',
    lockedTitle: 'Unlock recovery protection',
    lockedBody: 'Pinkeva Cloud + adds separation alerts, safe zones, 30-day history, and recovery tools to this tracker.',
    managePlan: 'View Pinkeva Cloud +',
    overview: 'Protection overview',
    lastLocation: 'Last location',
    locationCurrent: 'Current',
    locationStale: 'Needs an update',
    locationNever: 'Not reported yet',
    separationAlerts: 'Separation alerts',
    phoneProtection: 'Main phone',
    ready: 'Ready',
    stale: 'Needs an update',
    notConfigured: 'Not configured',
    replacement: 'Replacement benefit',
    eligible: 'Eligible',
    notEligible: 'Not eligible',
    on: 'On',
    off: 'Off',
    safeZones: 'Safe zones',
    safeZonesBody: 'Alerts are suppressed while the tracker remains inside a saved place.',
    addZone: 'Add safe zone',
    zoneLimit: '{{count}} of 20 zones',
    emptyZonesTitle: 'No safe zones yet',
    emptyZonesBody: 'Add Home, Work, or another place where this tracker can stay safely.',
    loading: 'Loading protection…',
    loadError: 'Protection details could not be loaded.',
    retry: 'Try again',
    trackerInside: 'Tracker was inside',
    trackerOutside: 'Tracker was outside',
    awaitingEvaluation: 'Awaiting first evaluation',
    lastEvaluated: 'Last checked {{date}}',
    paused: 'Paused',
    newZone: 'New safe zone',
    editZone: 'Edit safe zone',
    zoneName: 'Name',
    latitude: 'Latitude',
    longitude: 'Longitude',
    radius: 'Radius in metres',
    radiusHint: 'Minimum radius: 50 metres',
    useTrackerLocation: 'Use tracker location',
    invalidName: 'Enter a safe-zone name of up to 80 characters.',
    invalidCoordinates: 'Enter valid latitude and longitude coordinates.',
    invalidRadius: 'Radius must be a whole number between 50 and 100,000 metres.',
    zoneCreated: 'Safe zone added',
    zoneUpdated: 'Safe zone updated',
    zoneDeleted: 'Safe zone deleted',
    deleteTitle: 'Delete safe zone?',
    deleteBody: '{{name}} will stop protecting this saved place.',
    deleteAction: 'Delete',
    saveError: 'The safe zone could not be saved. Please try again.',
    limitError: 'This tracker already has the maximum of 20 safe zones.',
    homeTitle: 'Recovery protection',
    homeBody: 'Safe zones and phone-aware separation alerts are active.',
    homeLocked: 'Add phone-aware alerts and safe zones with Pinkeva Cloud +.',
  },
  pt: {
    title: 'Proteção',
    activeTitle: 'A proteção ligada ao telemóvel está ativa',
    activeBody: 'A Pinkeva combina o telemóvel, os relatórios do localizador e as zonas seguras para reduzir falsos alertas.',
    lockedTitle: 'Desbloqueie a proteção de recuperação',
    lockedBody: 'O Pinkeva Cloud + adiciona alertas de afastamento, zonas seguras, histórico de 30 dias e ferramentas de recuperação a este localizador.',
    managePlan: 'Ver Pinkeva Cloud +',
    overview: 'Resumo da proteção',
    lastLocation: 'Última localização',
    locationCurrent: 'Atual',
    locationStale: 'Precisa de atualização',
    locationNever: 'Ainda não comunicada',
    separationAlerts: 'Alertas de afastamento',
    phoneProtection: 'Telemóvel principal',
    ready: 'Pronto',
    stale: 'Precisa de atualização',
    notConfigured: 'Não configurado',
    replacement: 'Benefício de substituição',
    eligible: 'Elegível',
    notEligible: 'Não elegível',
    on: 'Ativo',
    off: 'Desativo',
    safeZones: 'Zonas seguras',
    safeZonesBody: 'Os alertas são silenciados enquanto o localizador permanece num local guardado.',
    addZone: 'Adicionar zona segura',
    zoneLimit: '{{count}} de 20 zonas',
    emptyZonesTitle: 'Ainda não existem zonas seguras',
    emptyZonesBody: 'Adicione Casa, Trabalho ou outro local onde este localizador possa permanecer em segurança.',
    loading: 'A carregar proteção…',
    loadError: 'Não foi possível carregar os detalhes da proteção.',
    retry: 'Tentar novamente',
    trackerInside: 'O localizador estava dentro',
    trackerOutside: 'O localizador estava fora',
    awaitingEvaluation: 'A aguardar a primeira avaliação',
    lastEvaluated: 'Última verificação: {{date}}',
    paused: 'Em pausa',
    newZone: 'Nova zona segura',
    editZone: 'Editar zona segura',
    zoneName: 'Nome',
    latitude: 'Latitude',
    longitude: 'Longitude',
    radius: 'Raio em metros',
    radiusHint: 'Raio mínimo: 50 metros',
    useTrackerLocation: 'Usar localização do localizador',
    invalidName: 'Introduza um nome com até 80 caracteres.',
    invalidCoordinates: 'Introduza coordenadas de latitude e longitude válidas.',
    invalidRadius: 'O raio deve ser um número inteiro entre 50 e 100 000 metros.',
    zoneCreated: 'Zona segura adicionada',
    zoneUpdated: 'Zona segura atualizada',
    zoneDeleted: 'Zona segura eliminada',
    deleteTitle: 'Eliminar zona segura?',
    deleteBody: '{{name}} deixará de proteger este local guardado.',
    deleteAction: 'Eliminar',
    saveError: 'Não foi possível guardar a zona segura. Tente novamente.',
    limitError: 'Este localizador já tem o máximo de 20 zonas seguras.',
    homeTitle: 'Proteção de recuperação',
    homeBody: 'As zonas seguras e os alertas de afastamento estão ativos.',
    homeLocked: 'Adicione alertas ligados ao telemóvel e zonas seguras com o Pinkeva Cloud +.',
  },
  fr: {
    title: 'Protection',
    activeTitle: 'La protection liée au téléphone est active',
    activeBody: 'Pinkeva combine votre téléphone, les signalements du traceur et les zones sûres pour réduire les fausses alertes.',
    lockedTitle: 'Débloquez la protection de récupération',
    lockedBody: 'Pinkeva Cloud + ajoute à ce traceur les alertes d’éloignement, les zones sûres, 30 jours d’historique et les outils de récupération.',
    managePlan: 'Voir Pinkeva Cloud +',
    overview: 'Aperçu de la protection',
    lastLocation: 'Dernière position',
    locationCurrent: 'À jour',
    locationStale: 'Mise à jour nécessaire',
    locationNever: 'Pas encore signalée',
    separationAlerts: 'Alertes d’éloignement',
    phoneProtection: 'Téléphone principal',
    ready: 'Prêt',
    stale: 'Mise à jour nécessaire',
    notConfigured: 'Non configuré',
    replacement: 'Avantage remplacement',
    eligible: 'Éligible',
    notEligible: 'Non éligible',
    on: 'Activées',
    off: 'Désactivées',
    safeZones: 'Zones sûres',
    safeZonesBody: 'Les alertes sont suspendues tant que le traceur reste dans un lieu enregistré.',
    addZone: 'Ajouter une zone sûre',
    zoneLimit: '{{count}} zones sur 20',
    emptyZonesTitle: 'Aucune zone sûre',
    emptyZonesBody: 'Ajoutez Maison, Travail ou un autre lieu où ce traceur peut rester en sécurité.',
    loading: 'Chargement de la protection…',
    loadError: 'Impossible de charger les détails de la protection.',
    retry: 'Réessayer',
    trackerInside: 'Le traceur était à l’intérieur',
    trackerOutside: 'Le traceur était à l’extérieur',
    awaitingEvaluation: 'En attente de la première évaluation',
    lastEvaluated: 'Dernière vérification : {{date}}',
    paused: 'En pause',
    newZone: 'Nouvelle zone sûre',
    editZone: 'Modifier la zone sûre',
    zoneName: 'Nom',
    latitude: 'Latitude',
    longitude: 'Longitude',
    radius: 'Rayon en mètres',
    radiusHint: 'Rayon minimum : 50 mètres',
    useTrackerLocation: 'Utiliser la position du traceur',
    invalidName: 'Saisissez un nom de 80 caractères maximum.',
    invalidCoordinates: 'Saisissez des coordonnées de latitude et longitude valides.',
    invalidRadius: 'Le rayon doit être un nombre entier compris entre 50 et 100 000 mètres.',
    zoneCreated: 'Zone sûre ajoutée',
    zoneUpdated: 'Zone sûre mise à jour',
    zoneDeleted: 'Zone sûre supprimée',
    deleteTitle: 'Supprimer la zone sûre ?',
    deleteBody: '{{name}} ne protégera plus ce lieu enregistré.',
    deleteAction: 'Supprimer',
    saveError: 'Impossible d’enregistrer la zone sûre. Réessayez.',
    limitError: 'Ce traceur possède déjà le maximum de 20 zones sûres.',
    homeTitle: 'Protection de récupération',
    homeBody: 'Les zones sûres et les alertes d’éloignement sont actives.',
    homeLocked: 'Ajoutez les alertes liées au téléphone et les zones sûres avec Pinkeva Cloud +.',
  },
  de: {
    title: 'Schutz',
    activeTitle: 'Telefonbasierter Schutz ist aktiv',
    activeBody: 'Pinkeva kombiniert Telefon, Tracker-Berichte und sichere Zonen, um Fehlalarme zu reduzieren.',
    lockedTitle: 'Wiederfinde-Schutz freischalten',
    lockedBody: 'Pinkeva Cloud + ergänzt diesen Tracker um Entfernungswarnungen, sichere Zonen, 30 Tage Verlauf und Wiederfinde-Werkzeuge.',
    managePlan: 'Pinkeva Cloud + ansehen',
    overview: 'Schutzübersicht',
    lastLocation: 'Letzter Standort',
    locationCurrent: 'Aktuell',
    locationStale: 'Aktualisierung nötig',
    locationNever: 'Noch nicht gemeldet',
    separationAlerts: 'Entfernungswarnungen',
    phoneProtection: 'Haupttelefon',
    ready: 'Bereit',
    stale: 'Aktualisierung nötig',
    notConfigured: 'Nicht eingerichtet',
    replacement: 'Ersatzvorteil',
    eligible: 'Berechtigt',
    notEligible: 'Nicht berechtigt',
    on: 'Ein',
    off: 'Aus',
    safeZones: 'Sichere Zonen',
    safeZonesBody: 'Warnungen werden unterdrückt, solange der Tracker an einem gespeicherten Ort bleibt.',
    addZone: 'Sichere Zone hinzufügen',
    zoneLimit: '{{count}} von 20 Zonen',
    emptyZonesTitle: 'Noch keine sicheren Zonen',
    emptyZonesBody: 'Fügen Sie Zuhause, Arbeit oder einen anderen sicheren Ort für diesen Tracker hinzu.',
    loading: 'Schutz wird geladen…',
    loadError: 'Die Schutzdetails konnten nicht geladen werden.',
    retry: 'Erneut versuchen',
    trackerInside: 'Tracker war innerhalb',
    trackerOutside: 'Tracker war außerhalb',
    awaitingEvaluation: 'Erste Prüfung steht aus',
    lastEvaluated: 'Zuletzt geprüft: {{date}}',
    paused: 'Pausiert',
    newZone: 'Neue sichere Zone',
    editZone: 'Sichere Zone bearbeiten',
    zoneName: 'Name',
    latitude: 'Breitengrad',
    longitude: 'Längengrad',
    radius: 'Radius in Metern',
    radiusHint: 'Mindestradius: 50 Meter',
    useTrackerLocation: 'Tracker-Standort verwenden',
    invalidName: 'Geben Sie einen Namen mit höchstens 80 Zeichen ein.',
    invalidCoordinates: 'Geben Sie gültige Breiten- und Längengrade ein.',
    invalidRadius: 'Der Radius muss eine ganze Zahl zwischen 50 und 100.000 Metern sein.',
    zoneCreated: 'Sichere Zone hinzugefügt',
    zoneUpdated: 'Sichere Zone aktualisiert',
    zoneDeleted: 'Sichere Zone gelöscht',
    deleteTitle: 'Sichere Zone löschen?',
    deleteBody: '{{name}} schützt diesen gespeicherten Ort danach nicht mehr.',
    deleteAction: 'Löschen',
    saveError: 'Die sichere Zone konnte nicht gespeichert werden. Bitte erneut versuchen.',
    limitError: 'Dieser Tracker hat bereits das Maximum von 20 sicheren Zonen.',
    homeTitle: 'Wiederfinde-Schutz',
    homeBody: 'Sichere Zonen und telefonbasierte Entfernungswarnungen sind aktiv.',
    homeLocked: 'Telefonbasierte Warnungen und sichere Zonen mit Pinkeva Cloud + hinzufügen.',
  },
  zh: {
    title: '保护',
    activeTitle: '手机感知保护已开启',
    activeBody: 'Pinkeva 会结合手机、追踪器报告和安全区域，减少误报。',
    lockedTitle: '解锁找回保护',
    lockedBody: 'Pinkeva Cloud + 可为此追踪器添加远离提醒、安全区域、30 天历史记录和找回工具。',
    managePlan: '查看 Pinkeva Cloud +',
    overview: '保护概览',
    lastLocation: '最后位置',
    locationCurrent: '最新',
    locationStale: '需要更新',
    locationNever: '尚未报告',
    separationAlerts: '远离提醒',
    phoneProtection: '主手机',
    ready: '已就绪',
    stale: '需要更新',
    notConfigured: '未配置',
    replacement: '更换权益',
    eligible: '符合条件',
    notEligible: '不符合条件',
    on: '开启',
    off: '关闭',
    safeZones: '安全区域',
    safeZonesBody: '追踪器留在已保存地点内时，不会发送提醒。',
    addZone: '添加安全区域',
    zoneLimit: '已用 {{count}} / 20 个区域',
    emptyZonesTitle: '尚无安全区域',
    emptyZonesBody: '添加家、工作地点或其他追踪器可安全停留的地方。',
    loading: '正在加载保护信息…',
    loadError: '无法加载保护详情。',
    retry: '重试',
    trackerInside: '追踪器上次在区域内',
    trackerOutside: '追踪器上次在区域外',
    awaitingEvaluation: '等待首次评估',
    lastEvaluated: '上次检查：{{date}}',
    paused: '已暂停',
    newZone: '新安全区域',
    editZone: '编辑安全区域',
    zoneName: '名称',
    latitude: '纬度',
    longitude: '经度',
    radius: '半径（米）',
    radiusHint: '最小半径：50 米',
    useTrackerLocation: '使用追踪器位置',
    invalidName: '请输入不超过 80 个字符的名称。',
    invalidCoordinates: '请输入有效的纬度和经度。',
    invalidRadius: '半径必须是 50 到 100,000 米之间的整数。',
    zoneCreated: '已添加安全区域',
    zoneUpdated: '已更新安全区域',
    zoneDeleted: '已删除安全区域',
    deleteTitle: '删除安全区域？',
    deleteBody: '{{name}} 将不再保护此已保存地点。',
    deleteAction: '删除',
    saveError: '无法保存安全区域，请重试。',
    limitError: '此追踪器已达到 20 个安全区域的上限。',
    homeTitle: '找回保护',
    homeBody: '安全区域和手机感知远离提醒已开启。',
    homeLocked: '使用 Pinkeva Cloud + 添加手机感知提醒和安全区域。',
  },
  it: {
    title: 'Protezione',
    activeTitle: 'La protezione collegata al telefono è attiva',
    activeBody: 'Pinkeva combina telefono, segnalazioni del tracker e zone sicure per ridurre i falsi avvisi.',
    lockedTitle: 'Sblocca la protezione di recupero',
    lockedBody: 'Pinkeva Cloud + aggiunge a questo tracker avvisi di separazione, zone sicure, cronologia di 30 giorni e strumenti di recupero.',
    managePlan: 'Vedi Pinkeva Cloud +',
    overview: 'Riepilogo protezione',
    lastLocation: 'Ultima posizione',
    locationCurrent: 'Attuale',
    locationStale: 'Da aggiornare',
    locationNever: 'Non ancora segnalata',
    separationAlerts: 'Avvisi di separazione',
    phoneProtection: 'Telefono principale',
    ready: 'Pronto',
    stale: 'Da aggiornare',
    notConfigured: 'Non configurato',
    replacement: 'Vantaggio sostituzione',
    eligible: 'Idoneo',
    notEligible: 'Non idoneo',
    on: 'Attivi',
    off: 'Disattivi',
    safeZones: 'Zone sicure',
    safeZonesBody: 'Gli avvisi vengono sospesi finché il tracker resta in un luogo salvato.',
    addZone: 'Aggiungi zona sicura',
    zoneLimit: '{{count}} zone su 20',
    emptyZonesTitle: 'Nessuna zona sicura',
    emptyZonesBody: 'Aggiungi Casa, Lavoro o un altro luogo in cui il tracker può restare al sicuro.',
    loading: 'Caricamento protezione…',
    loadError: 'Impossibile caricare i dettagli della protezione.',
    retry: 'Riprova',
    trackerInside: 'Il tracker era all’interno',
    trackerOutside: 'Il tracker era all’esterno',
    awaitingEvaluation: 'In attesa della prima valutazione',
    lastEvaluated: 'Ultimo controllo: {{date}}',
    paused: 'In pausa',
    newZone: 'Nuova zona sicura',
    editZone: 'Modifica zona sicura',
    zoneName: 'Nome',
    latitude: 'Latitudine',
    longitude: 'Longitudine',
    radius: 'Raggio in metri',
    radiusHint: 'Raggio minimo: 50 metri',
    useTrackerLocation: 'Usa posizione del tracker',
    invalidName: 'Inserisci un nome di massimo 80 caratteri.',
    invalidCoordinates: 'Inserisci coordinate di latitudine e longitudine valide.',
    invalidRadius: 'Il raggio deve essere un numero intero tra 50 e 100.000 metri.',
    zoneCreated: 'Zona sicura aggiunta',
    zoneUpdated: 'Zona sicura aggiornata',
    zoneDeleted: 'Zona sicura eliminata',
    deleteTitle: 'Eliminare la zona sicura?',
    deleteBody: '{{name}} non proteggerà più questo luogo salvato.',
    deleteAction: 'Elimina',
    saveError: 'Impossibile salvare la zona sicura. Riprova.',
    limitError: 'Questo tracker ha già il massimo di 20 zone sicure.',
    homeTitle: 'Protezione di recupero',
    homeBody: 'Le zone sicure e gli avvisi collegati al telefono sono attivi.',
    homeLocked: 'Aggiungi avvisi collegati al telefono e zone sicure con Pinkeva Cloud +.',
  },
  es: {
    title: 'Protección',
    activeTitle: 'La protección vinculada al teléfono está activa',
    activeBody: 'Pinkeva combina el teléfono, los informes del localizador y las zonas seguras para reducir falsas alertas.',
    lockedTitle: 'Desbloquea la protección de recuperación',
    lockedBody: 'Pinkeva Cloud + añade a este localizador alertas de separación, zonas seguras, historial de 30 días y herramientas de recuperación.',
    managePlan: 'Ver Pinkeva Cloud +',
    overview: 'Resumen de protección',
    lastLocation: 'Última ubicación',
    locationCurrent: 'Actual',
    locationStale: 'Necesita actualizarse',
    locationNever: 'Aún no informada',
    separationAlerts: 'Alertas de separación',
    phoneProtection: 'Teléfono principal',
    ready: 'Listo',
    stale: 'Necesita actualizarse',
    notConfigured: 'No configurado',
    replacement: 'Ventaja de sustitución',
    eligible: 'Elegible',
    notEligible: 'No elegible',
    on: 'Activadas',
    off: 'Desactivadas',
    safeZones: 'Zonas seguras',
    safeZonesBody: 'Las alertas se silencian mientras el localizador permanezca en un lugar guardado.',
    addZone: 'Añadir zona segura',
    zoneLimit: '{{count}} de 20 zonas',
    emptyZonesTitle: 'Aún no hay zonas seguras',
    emptyZonesBody: 'Añade Casa, Trabajo u otro lugar donde este localizador pueda permanecer seguro.',
    loading: 'Cargando protección…',
    loadError: 'No se pudieron cargar los detalles de protección.',
    retry: 'Reintentar',
    trackerInside: 'El localizador estaba dentro',
    trackerOutside: 'El localizador estaba fuera',
    awaitingEvaluation: 'Esperando la primera evaluación',
    lastEvaluated: 'Última comprobación: {{date}}',
    paused: 'En pausa',
    newZone: 'Nueva zona segura',
    editZone: 'Editar zona segura',
    zoneName: 'Nombre',
    latitude: 'Latitud',
    longitude: 'Longitud',
    radius: 'Radio en metros',
    radiusHint: 'Radio mínimo: 50 metros',
    useTrackerLocation: 'Usar ubicación del localizador',
    invalidName: 'Introduce un nombre de hasta 80 caracteres.',
    invalidCoordinates: 'Introduce coordenadas de latitud y longitud válidas.',
    invalidRadius: 'El radio debe ser un número entero entre 50 y 100.000 metros.',
    zoneCreated: 'Zona segura añadida',
    zoneUpdated: 'Zona segura actualizada',
    zoneDeleted: 'Zona segura eliminada',
    deleteTitle: '¿Eliminar zona segura?',
    deleteBody: '{{name}} dejará de proteger este lugar guardado.',
    deleteAction: 'Eliminar',
    saveError: 'No se pudo guardar la zona segura. Inténtalo de nuevo.',
    limitError: 'Este localizador ya tiene el máximo de 20 zonas seguras.',
    homeTitle: 'Protección de recuperación',
    homeBody: 'Las zonas seguras y las alertas vinculadas al teléfono están activas.',
    homeLocked: 'Añade alertas vinculadas al teléfono y zonas seguras con Pinkeva Cloud +.',
  },
};

export function interpolateProtectionCopy(
  template: string,
  values: Record<string, string>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => values[key] ?? `{{${key}}}`);
}

export function useProtectionCopy(): ProtectionCopy {
  const { language } = useI18n();
  return copies[language];
}
