#pragma once
#ifndef CONFIG_PM_ENABLE
#define CONFIG_PM_ENABLE 1
#endif
#ifndef CONFIG_PINQEVA_BUZZER_GPIO
#define CONFIG_PINQEVA_BUZZER_GPIO 25
#endif
#define CONFIG_PINQEVA_MAINTENANCE_BUTTON_GPIO 0
#define CONFIG_PINQEVA_BUZZER_FREQUENCY_HZ 4000
